version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: eixomano_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eixomano101
      POSTGRES_DB: eixomano
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: eixomano_backend
    restart: always
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://postgres:eixomano101@db:5432/eixomano
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eixomano_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
